version: '3'

services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile.dev
    container_name: remitano-videos-db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - dbremitano:/data/postgres-remitano-videos
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: remitano-videos-nginx
    ports:
      - 3300:80
    depends_on:
      - api
      - client
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: remitano-videos-api
    volumes:
      - ./server:/app
    environment:
      PGHOST: ${POSTGRES_HOST}
      PGDATABASE: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: ${POSTGRES_PORT}
      SECRET_KEY: ${SECRET_KEY}
      LOCAL_PORT: ${LOCAL_PORT}
    depends_on:
      - postgres
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: remitano-videos-client
    volumes:
      - /app/node_modules
      - ./client:/app
volumes:
  dbremitano:
    external: true
