version: '3'

services:
  client:
    image: 'trunglinh53/remitano-videos-client'
    mem_limit: 256m
    hostname: client
  server:
    image: 'trunglinh53/remitano-videos-server'
    mem_limit: 256m
    hostname: api
    environment:
      PGHOST: ${PGHOST}
      PGDATABASE: ${PGDATABASE}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGPORT: ${PGPORT}
      SECRET_KEY: ${SECRET_KEY}
  nginx:
    image: 'trunglinh53/remitano-videos-nginx'
    mem_limit: 256m
    hostname: nginx
    ports:
      - 80:80
