version: '3'

services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - dbremitano:/data/postgres-remitano-videos
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 3300:80
    depends_on:
      - api
      - client
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
    environment:
      PGHOST: ${POSTGRES_HOST}
      PGDATABASE: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: ${POSTGRES_PORT}
      SECRET_KEY: ${SECRET_KEY}
      ORIGIN_URL: ${ORIGIN_URL}
    depends_on:
      - postgres
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  # tests:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /app/node_modules
  #     - ./client:/app
  #   command: ['npm', 'run', 'test']
volumes:
  dbremitano:
    external: true
