FROM golang:1.22

WORKDIR /app

RUN go install github.com/cosmtrek/air@latest

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download && go mod verify

# Copy the source from the current directory to the workspace
COPY . .

# firstly find `.air.toml` in current directory, if not found, use defaults
# RUN go get github.com/cosmtrek/air
# RUN air init
# RUN go build -v -o /usr/local/bin/app ./...

# Expose port 8080 to the outside world
EXPOSE 8080

CMD [ "/go/bin/air" ]
# CMD ["air", "-c", ".air.toml"]
# CMD ["go", "run", "main.go"]
# CMD ["app"]
