# yaml-language-server: $schema=https://json.schemastore.org/github-actions.json
name: Deploy Remitano Videos

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # - name: Build test images
      #   run: docker build -t trungnd3/remitano-videos-client-test -f ./client/Dockerfile.dev ./client

      # - name: Run tests
      #   run: docker run -e CI=true trungnd3/remitano-videos-client-test npm run test

      - name: Build multiple project images
        run: |
          docker build -t trunglinh53/remitano-videos-client ./client
          docker build -t trunglinh53/remitano-videos-nginx ./nginx
          docker build -t trunglinh53/remitano-videos-server ./server

      - name: Push images to docker hub
        run: |
          docker push trunglinh53/remitano-videos-client
          docker push trunglinh53/remitano-videos-nginx
          docker push trunglinh53/remitano-videos-server

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EBS
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: remitano-videos
          environment_name: Remitano-videos-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-1-391898470917
          existing_bucket_path: remitano-videos
          region: ap-southeast-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
